title = "Local配置"
app_name = "xxx"
sql_driver = "sqlite"
debug = true


[telemetry]
log.level = "DEBUG"
log.filename = "app.log"
metric.endpoint = "http://localhost:4317"
trace.endpoint = "http://localhost:4317"

[sqlite]
db = "/test.db"


[mysql]
host = ""
port = 330
db = "test"
user = ""
passwd = ""
charset = ""
